-- Supabase SQL Editor에서 한 번 실행하세요.
-- 일정 추가·수정·삭제 이력을 코치별로 기록합니다.

create table if not exists public.schedule_history (
  id bigint generated by default as identity primary key,
  schedule_id bigint,
  action text not null check (action in ('created', 'updated', 'deleted')),
  actor_name text not null,
  target_coach_name text not null,
  student_name text,
  description text,
  snapshot jsonb,
  created_at timestamptz not null default now()
);

create index if not exists schedule_history_target_coach_created_at_idx
  on public.schedule_history (target_coach_name, created_at desc);

create index if not exists schedule_history_schedule_id_idx
  on public.schedule_history (schedule_id);
